### ISSUE TITLE
Verbos e Nouns

### ISSUE THREAD

**Issue by suemi-higuchi** [cpdoc/dhbb-nlp#11]
No [15.conllu](https://github.com/cpdoc/dhbb-nlp/blob/master/udp/15.conllu):

- VERB ao invés de NOUN na sentença 17:
`4	repórter	repórter	VERB	_	Number=Sing	2	acl	_	SpacesAfter=\n`

- na sentença 23:
`10	autodidata	autodidatar	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	1	conj	_	SpaceAfter=No`

- na sentença 28:
`31	pai	pair	VERB	_	Gender=Masc|Number=Sing	28	appos	_	&vinculo-fam`

- NOUN ao invés de VERB na sentença 17:
```
36	apoiaria	apoiaria	NOUN	_	Mood=Cnd|Number=Sing|Person=3|VerbForm=Fin	34	appos	_	_
37	Getúlio	Getúlio	PROPN	_	Gender=Masc|Number=Sing	36	obj	_	_
38	Vargas	Vargas	PROPN	_	Number=Sing	37	flat:name	_	SpaceAfter=No
```

Devo tentar corrigir manualmente?

**Comment by arademaker** [comment]
discussão antiga no contexto dos experimentos que fizemos para o paper http://arademaker.github.io/bibliography/lrec-2018.html. A discussão acabou sendo quando e se corrigir árvores quando o foco do experimento era a classificação de quais relações sintáticas eram introduzidas pelos `appos`. acho que esta discussão é agora irrelevante para nosso propósito com o udp-mini
