### ISSUE TITLE
Uso de compound e flat para Comissões e afins?

### ISSUE THREAD

**Issue by suemi-higuchi** [cpdoc/dhbb-nlp#13]
Vi que vocês já falaram alguma coisa sobre flat, compound e fixed, mas ainda tenho dúvidas.
Estabelecemos que "federal" é compound de "deputado" (deputado federal). Nos casos abaixo também? Seria algo assim como eu coloquei? 

Estou tentando entender aqui na [wiki](https://github.com/cpdoc/dhbb-nlp/wiki/Compound-e-flat). 
```
# A Comissão de Fiscalização Financeira e Tomada de Contas...
1 A 
2 Comissão 
3 de
4 Fiscalização - 2 - compound
5 Financeira - 4 - flat:name
6 e
7 Tomada - 4 - flat:name
8 de
9 Contas - 4 - flat:name
```

```
# As Comissões de Fiscalização Financeira e Comércio Exterior...
1 As 
2 Comissões 
3 de
4 Fiscalização - 2 - compound
5 Financeira - 4 - flat:name
6 e
7 Comércio - 4 - conj 
8 Exterior - 7 - flat:name
```

**Comment by arademaker** [comment]
Outra discussão antiga sobre MWE de nomes. Uso de compound segundo discussões mais recentes de UD me parece errado. nomes longos como títulos de comissões tem sintaxe interna. NER é outra camada de anotação. 

De qq modo, vou fechar isso. No novo sample UD-mini podemos ter outro issue para revisão sistemática de nomes.
