### ISSUE TITLE
Onde está o root?

### ISSUE THREAD

**Issue by suemi-higuchi** [cpdoc/dhbb-nlp#15]
Dúvida rápida.
Nestas sentenças abaixo:

22.conllu:2 

> Seu irmão, Sílvio de Andrade Abreu, foi deputado estadual por Minas Gerais de 1971 a 1975, e seu sobrinho Sílvio de Andrade Abreu Júnior, passou igualmente a representar esse estado na Câmara dos Deputados a partir de 1975.

Aqui o UD errou feio ao dizer que deputado é verbo; daí eu fui no UDPipe e troquei por secretário e ele passou a dizer que secretário é o root (a função de "foi" está como auxiliar).
O Palavras acertou no deputados e colocou "foi" como root.

22.conlllu:3

> Ainda como coronel, Hugo Abreu foi para os EUA, onde atuou como assessor da delegação brasileira na Junta Interamericana de Defesa e na Comissão Mista de Defesa Brasil-Estados Unidos.

Aqui o UD colocou o "foi" como verbo, e por conseguinte, root.

Todos os dois verbos "foi" são root? O UD errou no primeiro caso?

**Comment by arademaker** [comment]
discussão longa sobre os casos de copula. De fato, durante revisão do mini certamente teremos situações como estas para serem revisadas, com recorte para selecionar para discussão em alguma conversa com o @leoalenc. Mas esta discussão vou considerar encerrada.
