### ISSUE TITLE
paraphrase

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb-nlp#16]
@claudiafreitas disse:

Para a EI, talvez seja necessário criar um outro DHBB, com alguns pós-processamentos, para podermos fazer a EI. Exemplos de pós processamentos:

a) criar cópias do nome do verbete Biográfico para ocupar o lugar do sujeito oculto em frases que iniciam parágrafo (sim, precisaremos testar isso, mas já registramos aqui)

b) "reconstruir" NEs que estão em coordenação (que é o caso do issue acima). Na frase abaixo, precisaremos reconstruir NEs que estejam coordenadas, levando em conta o lema. Ou seja, a frase abaixo deveria poder gerar a seguinte frase pós-processada:

> As Comissões de Fiscalização Financeira e [Comissão] [de] Comércio Exterior declararam...

**Comment by vcvpaiva** [comment]
Pro mini-DHBB nao deve ser dificil fazer b) acima.

**Comment by arademaker** [comment]
não me interessa muito este tipo de abordagem, a não ser que modificações no texto possam vir a indicar sugestões para guidelines de edição do DHBB (@jaquepz ?). Mas do ponto de vista de processamento dos textos, prefiro focar primeiro no esforço de tentar fazer os parsers fazerem análises sintáticas corretas dos textos como eles estão, com todas as diversidades de estruturas linguisticas que encontramos, sem transformações. Pelo menos neste primeiro momento.

Acho que existem várias aplicação de PLN possíveis com o DHBB, simplificação de textos como feito por https://sites.icmc.usp.br/taspardo/DocEng2008-AluisioEtAl.pdf ou identificação de bias como em https://arxiv.org/abs/1911.09709 podem ser trabalhos interessantes no DHBB, sem dúvida. 

Este issue foi criado em 2017, era outro contexto de pesquisa.
