### ISSUE TITLE
post-processing CoNLL-U files

### ISSUE THREAD

**Issue by lucasrct** [cpdoc/dhbb-nlp#49]
Até sexta (dia  15/5): Terminar de implementar a biblioteca de Prolog em Lisp baseado no livro recomendado.

Até Segunda: (dia 18/5): Fazer os ajustes na bib cl-conllu para, extrair as informações das sentenças no formato do prolog em lisp.

**Comment by arademaker** [comment]
@lucasrct muito importante vc manter o repo atualizado com seus códigos mesmo que parciais, assim posso te ajudar, comentar e sugerir direção.

**Comment by lucasrct** [comment]
@arademaker pronto. Coloquei um README com algumas observações

**Comment by arademaker** [comment]
ja estamos em 21 Maio...

**Comment by arademaker** [comment]
este issue está antigo e foi descontinuado com saida do @lucasrct. estamos abordando o problema de outra forma.
