### ISSUE TITLE
golden vs RAW

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb-nlp#63]
relacionado à tarefa https://github.com/cpdoc/test/issues/5

no commit 810e45650 introduz no repositório os arquivos golden do WKS. Identificamos uma diferença entre o 11262.raw e o conteúdo no wks/gt/0880fb70-d93b-11ea-bff2-05ea84f8fa50-0.json, arquivo referente ao 11262.raw importado para o WKS. 

1. esta diferença existe em todos os arquivos? aparentemente é apenas um `\n` no início. 
2. como podemos comparar de forma sistemática os arquivos para saber quando um RAW mudou (possivelmente porque o DHBB mudou, e a versão daquele arquivo no WKS precisaria ser atualizada? 
3. se estas diferenças sempre acontecem, será que podemos pensar em uma forma de 'realinhar' as strings?

**Comment by arademaker** [comment]
Olhando alguns casos eu tenho uma hipótese. Parece que estes documentos que foram importados para o WKS foram anteriores a uma reorganização que fiz na geração dos arquivos RAW. Anteriormente, o RAW eram apenas o output a partir dos respectivos arquivos em https://github.com/cpdoc/dhbb/tree/master/text. Mas posteriormente, identificamos que algumas ferramentas de segmentação de sentenças se perdiam quando encontravam quebras de linhas dentro de frases, caso que ocorre , por exemplo, em

https://github.com/cpdoc/dhbb/blob/master/text/1005.text

A quebra de linha na coluna ~70-80 é neste caso desejável para facilitar a comparação entre versões dos arquivos no repositório DHBB. Linhas longas seriam difíceis de comparar. Formatando o texto em ~80 colunas, o diff entre versões é mais legível. Por exemplo:

https://github.com/cpdoc/dhbb/commit/023df76169e1830cda33ac8e466a4617e0c9e0cb#diff-31249dcf5d177e851a81070466850d1ad6e0e10efa9b3da284647552614f879a

Mas no RAW o que queremos é não ter quebras de linhas dentro de frases, logo o código https://github.com/cpdoc/dhbb-nlp/blob/master/raw/extract.awk#L33 cuida de juntar linhas consecutivas que tenham algum caracter diferente de espaço. Isto é, produzem um parágrafo por linha.

eu acho que importamos para o WKS versões RAW anteriormente a este novo processamento de juntar linhas do mesmo parágrafo....  Temos que identificar os arquivos que estão neste caso e talvez remove-los do WKS e substitui-los por novos arquivos RAW.  

Então esta tarefa trata de identifica estes arquivos no wks/gt que tem conteúdo diferente do respectivo RAW.

**Comment by wellington36** [comment]
Temos a função verificadora de textos NLU e WKS (encontra diferença ou inexistência) no https://github.com/cpdoc/test/blob/issue-5-rev/app/NER.hs e usaremos para verificar os arquivos adicionados e corrigir os que não tem mesmo texto.

**Comment by arademaker** [comment]
poderia listar aqui os casos diferentes?

**Comment by wellington36** [comment]
Os casos:

 4541.json,  4013.json,  1831.json,  3568.json,  788.json,  11149.json,  699.json,  11853.json,  3127.json,  1103.json,  1125.json,  5702.json,  6122.json,  85.json,  906.json,  11241.json,  3029.json,  4129.json,  2285.json,  5032.json,  148.json,  2148.json,  11497.json,  1320.json,  5177.json,  2626.json,  10747.json,  1067.json,  2299.json,  5754.json,  1267.json,  3340.json,  2521.json,  516.json,  1.json,  61.json,  2120.json,  2492.json,  2493.json,  2639.json,  2753.json,  3084.json,  3142.json,  3317.json,  3438.json,  3702.json,  246.json,  3721.json,  3783.json,  3853.json,  4391.json,  4434.json,  4494.json,  4608.json,  4799.json,  4878.json,  5762.json,  1183.json,  5975.json,  6167.json,  6205.json,  8813.json,  10824.json,  10926.json,  10968.json,  11293.json,  11313.json,  11323.json,  1395.json,  11576.json,  12117.json,  1655.json,  1829.json,  1889.json,  1950.json,  1958.json,  8.json,  5919.json,  3739.json,  5723.json,  5993.json,  8731.json,  6319.json,  1802.json,  6026.json,  5999.json,  5813.json,  5810.json,  4933.json,  5927.json,  15.json,

**Comment by arademaker** [comment]
arquivos apagados do WKS.
