### ISSUE TITLE
mini-dhbb: temporal processing

### ISSUE THREAD

**Issue by vcvpaiva** [cpdoc/dhbb-nlp#65]
please run heideltime on this 2k sentences.

**Comment by arademaker** [comment]
o que vc espera com isso? Temos várias outras tarefas possíveis. Qual seria a resposta? Como vc usará a resposta?

**Comment by arademaker** [comment]
Vide #54

**Comment by vcvpaiva** [comment]
well, having dates correctly separated is supposed to guide the parser. I would like to use the information from the heideltime to help us on the predicate-argument extraction from mini-dhbb. I also expect the running of this side-show to identify expressions in Portuguese that are about temporality that one doesn't have in English.
