### ISSUE TITLE
Bad segmentation in mini-dhbb

### ISSUE THREAD

**Issue by vcvpaiva** [cpdoc/dhbb-nlp#69]
https://github.com/cpdoc/dhbb-nlp/blob/e402e8037a7bed8febae0f0ef4fd750842ac47f7/udp-mini/10827.conllu

sent_id = 1
text = «José Roberto Batochio» nasceu em Dois

sent_id = 2
text = Córregos (SP) no dia 17 de abril de 1944, filho de José Francisco Batochio e de Dalva Vieira dos Santos Batochio.

**Comment by vcvpaiva** [comment]
another bad segmentation in 
https://github.com/cpdoc/dhbb-nlp/blob/e402e8037a7bed8febae0f0ef4fd750842ac47f7/udp-mini/12117.conllu

sent_id = 2
text = Diplomou-se em Ciências
sent_id = 3
text = Contábeis e cursou especialização em Gestão Comercial pela Faculdade Internacional de Curitiba (FACINTER).

**Comment by vcvpaiva** [comment]
https://github.com/cpdoc/dhbb-nlp/blob/e402e8037a7bed8febae0f0ef4fd750842ac47f7/udp-mini/12117.conllu

sent_id = 6
text = Filiou-se ao Partido Social
sent_id = 7
text = Cristão em 2009, pelo qual disputou uma cadeira na Câmara dos Deputados no pleito do ano seguinte.

**Comment by arademaker** [comment]
solved by 8c7558204 , duplicated from #68
