### ISSUE TITLE
Nomes próprios 

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb-nlp#7]
Para continuar discussão iniciada neste commit:

https://github.com/cpdoc/dhbb-nlp/commit/b4f35311d29151ac7ad58113d4b1e8c168474517

@GPPassos e @claudiafreitas  vamos continuar aqui ok ? Não temos ainda conclusão , vejam link que compartilhei

**Comment by arademaker** [comment]
Novamente, este issue é antigo e vou fechar. Na época não me parece termos convergido para nenhuma decisão. Por outro lado, discussões em UD permaneceram, para citar uma recente https://github.com/UniversalDependencies/UD_English-EWT/issues/133

Então nas decisões em ud-mini, teremos que levar em conta situação atual de UD.

**Comment by vcvpaiva** [comment]
nao me parece razoavel fechar o issue, uma vez q a discussao continua atual.

tb nao me parece que solucoes hibridas tenham sido muito consideradas. 
eu acho q nao faz sentido analisar nomes de pessoas, mas q faz algum sentido sim analisar nomes de organizacoes e de titulos de livros, filmes e outros.

**Comment by arademaker** [comment]
Fechei porque estes casos certamente irão ocorrer no mini, de forma mais concreta e teremos um `action item`: poderemos então analisar lá e decidir. Para cada decisão, eu quero tentar gerar uma documentação, podemos começar com o wiki aqui mas externalizar para o time de UD o mais rápido possível.
